type:
  name: "backgate"
ingress:
  enabled: true
  path: "/khaleesi.(core|api).GateKeeper"
  regex_path: true
  port: "grpc-web-envoy"
django:
  enabled: true
grpc_web:
  enabled: true
grpcui:
  enabled: true
