@startuml
actor user as user #lightpink;line:darkred;text:darkred

' SITE
cloud       "frontend"      as frontend     #lavender;line:darkviolet;text:darkviolet
collections "microservices" as microservice #lavender;line:darkviolet;text:darkviolet

' CORE
collections "core microservices" as core_microservice #lavender;line:darkviolet;text:darkviolet

' 3RD PARTY
card        "kubegres"   as kubegres   #bisque;line:saddlebrown;text:saddlebrown
card        "prometheus" as prometheus #bisque;line:saddlebrown;text:saddlebrown
card        "grafana"    as grafana    #bisque;line:saddlebrown;text:saddlebrown
collections "gRPC UI"    as grpcui     #bisque;line:saddlebrown;text:saddlebrown

' site connections
user      --> frontend          #saddlebrown;text:saddlebrown : https
frontend  --> core_microservice #darkviolet;text:darkviolet   : gGRPC
frontend  --> microservice      #darkviolet;text:darkviolet   : gGRPC

' kubegres connection
microservice      --> kubegres #saddlebrown;text:saddlebrown : PostgreSQL
core_microservice --> kubegres #saddlebrown;text:saddlebrown : PostgreSQL

' grpcui connection
user   --> grpcui            #saddlebrown;text:saddlebrown : https
grpcui --> microservice      #saddlebrown;text:saddlebrown : gGRPC
grpcui --> core_microservice #saddlebrown;text:saddlebrown : gGRPC

' prometheus connection
user       --> grafana           #saddlebrown;text:saddlebrown : https
grafana    --> prometheus        #saddlebrown;text:saddlebrown : http
prometheus --> microservice      #saddlebrown;text:saddlebrown : http
prometheus --> core_microservice #saddlebrown;text:saddlebrown : http
prometheus --> kubegres          #saddlebrown;text:saddlebrown : http
@enduml
