# khaleesi.ninja.
environment:
  #name: "required name"
  #domain: "required domain"
site:
  #name: "required name"
app:
  #name: "required name"
  #version: "required stable version"
  replicas: 1
  image_pull_policy: "Always"
  drop_database: false
type:
  #name: "required name"

# Kubernetes.
ingress:
  enabled: false
  path: "/"
  regex_path: false
  port: "app"
  root: false

# Django.
django:
  enabled: false

# Database.
kubegres:
  enabled: false
  image: postgres:14.1
  port: 5432

# Monitoring.
probe:
  http:
    enabled: false
    readiness: "/"
    liveness: "/"
    startup: "/"
  grpc:
    enabled: false

# gRPC.
grpcui:
  enabled: false
  version: "v1.2.0"
