addons:
  hostname: khaleesi-testing

matrix:
  include:
    - language: python
      python: 3.8
      services: postgresql
      env: BACKEND_PROJECT=base
      install: ./scripts/backend_install.sh
      script: ./scripts/backend_run.sh
      after_script: ./scripts/backend_after.sh
    - language: node_js
      node_js: 12
      install: npm --prefix frontend install
      script: ./scripts/frontend_run.sh
      after_script: ./scripts/frontend_after.sh
