ignore:
  - "backend/*/manage.py"
  - "backend/*/configuration"
  - "backend/*/migrations"
  - "backend/*/tests"
  - "backend/base/base_settings"
  - "frontend/src/serviceWorker.ts"
  - "frontend/src/index.tsx"
