ignore:
  # Frontend.
  - frontgate/core/src/core/reportWebVitals.ts
  - frontgate/core/src/index.tsx
  # Backend library.
  - backend/manage.py
  - backend/khaleesi/core/settings/**
  # Backend.
  - backend/*/*/*/migrations/**
  - backend/*/*/settings.py
  - backend/*/*/tests/**
