{
 "title": "{{ .Values.site.name }}",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(app, peer_site) (increase(khaleesi_incoming_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`OK: {{app}} called by {{peer_site}}`}}"
    },
    {
     "expr": "sum by(app, peer_site) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`NOK: {{app}} called by {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Incoming errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(app, peer_site, status) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{app}} called by {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(app, peer_site) (increase(khaleesi_outgoing_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`OK: {{app}} calling {{peer_site}}`}}"
    },
    {
     "expr": "sum by(app, peer_site) (increase(khaleesi_outgoing_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`NOK: {{app}} calling {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(app, peer_site, status) (increase(khaleesi_outgoing_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{app}} calling {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (app) (khaleesi_health{site=\"{{ .Values.site.name }}\", khaleesi_health=\"healthy\"}) > 0",
     "legendFormat": "{{`{{app}}: healthy`}}"
    },
    {
     "expr": "sum by (app) (khaleesi_health{site=\"{{ .Values.site.name }}\", khaleesi_health!=\"healthy\"}) > 0",
     "legendFormat": "{{`{{app}}: not healthy`}}"
    }
   ]
  },
  {
   "title": "Instance health errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (khaleesi_health, app) (khaleesi_health{khaleesi_health!=\"healthy\",site=\"{{ .Values.site.name }}\"}) > 0",
     "legendFormat": "{{`{{app}}: {{khaleesi_health}}`}}"
    }
   ]
  },
  {
   "title": "Instance Start/End",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (app, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", result=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{app}}: {{action_crud_type}} - success`}}"
    },
    {
     "expr": "sum by (app, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", result!=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{app}}: {{action_crud_type}} - {{result}}`}}"
    }
   ]
  },
  {
   "title": "Instance Start/End Problems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (app, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", result!=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{app}}: {{action_crud_type}} - {{result}}`}}"
    }
   ]
  }
 ]
}