[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "configuration.settings"

[mypy-*.migrations.*]
ignore_errors = True

[mypy-configuration.*]
ignore_errors = True

[mypy-manage]
ignore_errors = True

[mypy-base_settings.*]
ignore_errors = True