[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "configuration.settings"

[mypy-BACKEND_PROJECT.*.migrations.*]
ignore_errors = True

[mypy-BACKEND_PROJECT.configuration.*]
ignore_errors = True

[mypy-BACKEND_PROJECT.manage]
ignore_errors = True