apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: ingress-class-{{ .Values.environment }}
  labels:
    name: khaleesi-ninja
    environment: {{ .Values.environment }}
    type: infrastructure
    infrastructure: ingress-class
spec:
  controller: k8s.io/ingress-nginx
  parameters:
    kind: IngressParameters
    name: ingress-class
    namespace: khaleesi-ninja-{{ .Values.environment }}
    scope: Namespace
