name: Set JSON output
description: Set output from JSON file for use in dependent jobs
inputs:
  filename:
    description: The file to read into the output
    required: true
outputs:
  full-json:
    description: Full parsed content of the JSON file
    value: ${{ steps.generate-output.outputs.full-json }}
  deploy-json:
    description: Parsed content of the JSON file for deployments only
    value: ${{ steps.generate-output.outputs.deploy-json }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo Reading JSON from ${{ inputs.filename }}
    - id: generate-output
      shell: bash
      run: |
        FULL_JSON=$(echo $(cat ${{ inputs.filename }}))
        DEPLOY_JSON=$(echo $(sed '/"deploy": "false"/d' ${{ inputs.filename }}))
        echo "::set-output name=full-json::$FULL_JSON"
        echo "::set-output name=deploy-json::$DEPLOY_JSON"
    - shell: bash
      run: echo Full result is ${{ toJson(steps.generate-output.outputs.full-json) }}
