{{ if .Values.kubegres.development_credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gate.name }}-kubegres-credentials
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    infrastructure: kubegres
    gate: {{ .Values.gate.name }}
type: Opaque
stringData:
  superUserPassword: superUnsafeSecret
  replicationUserPassword: replicatedUnsafeSecret
{{ end }}
