apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gate.name }}-kubegres-configuration
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    infrastructure: kubegres
    gate: {{ .Values.gate.name }}
data:
  host: "{{ .Values.gate.name }}-kubegres"
  port: "{{ .Values.kubegres.port }}"
  superUser: postgres
