apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ .Values.site.name }}-kubegres"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}"
  labels:
    khaleesi-ninja: "app"
    infrastructure: "kubegres"
    site: "{{ .Values.site.name }}"
data:
  host: "{{ .Values.site.name }}-kubegres"
  port: "{{ .Values.kubegres.port }}"
  superUser: "postgres"
