apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gate }}-{{ .Values.service }}-deployment
  namespace: khaleesi-ninja-{{ .Values.environment }}
  labels:
    gate: {{ .Values.gate }}
    service: {{ .Values.service }}
    type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service }}{{ else }}micro{{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      gate: {{ .Values.gate }}
      service: {{ .Values.service }}
      type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service }}{{ else }}micro{{ end }}
  template:
    metadata:
      labels:
        gate: {{ .Values.gate }}
        service: {{ .Values.service }}
        type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service }}{{ else }}micro{{ end }}
    spec:
      containers:
        - name: deployment
          image: khaleesi-ninja/{{ .Values.gate }}/{{ .Values.service }}:{{ if eq .Values.environment "development" "integration" }}latest{{ else }}{{ .Values.version }}{{ end }}
          imagePullPolicy: {{ if eq .Values.environment "development" "integration" }}Never{{ else }}Always{{ end }}
          ports:
            - name: deployment
              containerPort: 8000
        {{- if eq .Values.service "backgate" }}
        - name: envoy
          image: khaleesi-ninja/infrastructure/envoy:latest
          imagePullPolicy: {{ if eq .Values.environment "development" "integration" }}Never{{ else }}Always{{ end }}
          ports:
            - name: envoy
              containerPort: 8010
        {{- end }}
        {{- if eq .Values.environment "development" "integration" }}
        {{- if ne .Values.service "frontgate" }}
        - name: grpcui
          image: fullstorydev/grpcui:latest
          imagePullPolicy: Always
          args: [ "-port=9000", "-plaintext", "localhost:8000" ]
          ports:
            - name: grpcui
              containerPort: 9000
        {{- end }}
        {{- end }}
