{{- if eq .Values.service "frontgate" "backgate" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.gate }}-{{ .Values.service }}-ingress
  namespace: khaleesi-ninja-{{ .Values.environment }}
  labels:
    gate: {{ .Values.gate }}
    service: {{ .Values.service }}
    type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service  }}{{ else }}micro{{ end }}
  {{- if eq .Values.service "backgate" }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  {{- end }}
spec:
  ingressClassName: ingress-class-{{ .Values.environment }}
  tls:
    - secretName: tls-certificate
      hosts:
      - {{ .Values.gate }}{{ if ne .Values.environment "production" }}.{{ .Values.environment }}{{ end }}.khaleesi.ninja
  rules:
    - host: {{ .Values.gate }}{{ if ne .Values.environment "production" }}.{{ .Values.environment }}{{ end }}.khaleesi.ninja
      http:
        paths:
          - path: /{{ if eq .Values.service "backgate" }}khaleesi\..*{{ end }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.gate }}-{{ .Values.service }}-service
                port:
                  name: service
{{- end }}
