apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-service
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: {{ .Values.type.name }}
spec:
  selector:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: {{ .Values.type.name }}
  ports:
    - name: service
      protocol: TCP
      port: 8000
      targetPort: deployment
    {{- if .Values.grpc_web.enabled }}
    - name: grpc-web-envoy
      protocol: TCP
      port: 8010
      targetPort: grpc-web-envoy
    {{- end }}
