apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gate }}-{{ .Values.service }}-service
  namespace: khaleesi-ninja-{{ .Values.environment }}
  labels:
    gate: {{ .Values.gate }}
    service: {{ .Values.service }}
    type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service }}{{ else }}micro{{ end }}
spec:
  selector:
    gate: {{ .Values.gate }}
    service: {{ .Values.service }}
    type: {{ if eq .Values.service "frontgate" "backgate" }}{{ .Values.service }}{{ else }}micro{{ end }}
  ports:
    - name: service
      protocol: TCP
      port: 8000
      targetPort: deployment
    {{- if eq .Values.service "backgate" }}
    - name: envoy
      protocol: TCP
      port: 8010
      targetPort: envoy
    {{- end }}
    {{- if eq .Values.environment "development" "integration" }}
    {{- if ne .Values.service "frontgate" }}
    - name: grpcui
      protocol: TCP
      port: 9000
      targetPort: grpcui
    {{- end }}
    {{- end }}
