# Generated by Django 4.2.3 on 2023-11-08 23:18

from django.db import migrations, models
import typing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.TextField()),
                ('status', models.TextField(default='UNKNOWN')),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('statusDetails', models.TextField()),
                ('itemsProcessed', models.IntegerField(default=0)),
                ('totalItems', models.IntegerField(default=0)),
                ('khaleesiVersion', models.IntegerField(default=0)),
                ('executionId', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
