# Generated by Django 4.0.5 on 2023-06-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.TextField(default='UNKNOWN')),
                ('executionId', models.BigIntegerField(default=-1)),
                ('status', models.TextField(default='UNKNOWN')),
                ('end', models.DateTimeField(auto_now=True)),
                ('itemsProcessed', models.IntegerField(default=0)),
                ('totalItems', models.IntegerField(default=0)),
                ('details', models.TextField(default='')),
            ],
        ),
    ]
