# Generated by Django 4.2.3 on 2023-08-07 17:05

import datetime
from django.db import migrations, models
import typing


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionTimelimit', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('actionBatchSize', models.IntegerField(default=1000)),
                ('cleanupIs', models.BooleanField(default=False)),
                ('cleanupDelay', models.DurationField(default=datetime.timedelta(0))),
                ('khaleesiVersion', models.IntegerField(default=0)),
                ('jobId', models.TextField()),
                ('executionId', models.TextField()),
                ('status', models.TextField(default='UNKNOWN')),
                ('end', models.DateTimeField()),
                ('statusDetails', models.TextField()),
                ('itemsProcessed', models.IntegerField(default=0)),
                ('totalItems', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
