# Generated by Django 4.0.5 on 2022-06-30 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_caller_request_id', models.BigIntegerField(default=0)),
                ('meta_caller_khaleesi_gate', models.TextField(default='UNKNOWN')),
                ('meta_caller_khaleesi_service', models.TextField(default='UNKNOWN')),
                ('meta_caller_grpc_service', models.TextField(default='UNKNOWN')),
                ('meta_caller_grpc_method', models.TextField(default='UNKNOWN')),
                ('meta_user_id', models.TextField(default='UNKNOWN')),
                ('meta_user_type', models.IntegerField(default=0)),
                ('meta_event_timestamp', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('meta_logged_timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta_logging_errors', models.TextField(blank=True)),
                ('target_type', models.TextField(default='UNKNOWN')),
                ('target_id', models.BigIntegerField(default=0)),
                ('target_owner', models.UUIDField(blank=True, null=True)),
                ('action_crud_type', models.IntegerField(default=0)),
                ('action_custom_type', models.TextField(default='UNKNOWN')),
                ('action_result', models.IntegerField(default=0)),
                ('action_details', models.TextField(default='UNKNOWN')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_caller_request_id', models.BigIntegerField(default=0)),
                ('meta_caller_khaleesi_gate', models.TextField(default='UNKNOWN')),
                ('meta_caller_khaleesi_service', models.TextField(default='UNKNOWN')),
                ('meta_caller_grpc_service', models.TextField(default='UNKNOWN')),
                ('meta_caller_grpc_method', models.TextField(default='UNKNOWN')),
                ('meta_user_id', models.TextField(default='UNKNOWN')),
                ('meta_user_type', models.IntegerField(default=0)),
                ('meta_event_timestamp', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('meta_logged_timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta_logging_errors', models.TextField(blank=True)),
                ('upstream_request_request_id', models.BigIntegerField(default=0)),
                ('upstream_request_khaleesi_gate', models.TextField(default='UNKNOWN')),
                ('upstream_request_khaleesi_service', models.TextField(default='UNKNOWN')),
                ('upstream_request_grpc_service', models.TextField(default='UNKNOWN')),
                ('upstream_request_grpc_method', models.TextField(default='UNKNOWN')),
                ('response_status', models.TextField(default='IN_PROGRESS')),
                ('response_event_timestamp', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('response_logged_timestamp', models.DateTimeField(auto_now=True)),
                ('response_logging_errors', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistryKhaleesiGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistryKhaleesiService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('khaleesi_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khaleesi_services', to='microservice.serviceregistrykhaleesigate')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistryGrpcService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('khaleesi_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_services', to='microservice.serviceregistrykhaleesiservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistryGrpcMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('grpc_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_methods', to='microservice.serviceregistrygrpcservice')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRegistryGrpcCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='microservice.serviceregistrygrpcmethod')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_by', to='microservice.serviceregistrygrpcmethod')),
            ],
        ),
    ]
