name: "Load all images"
description: "Load the images of all apps defined in the input."
inputs:
  apps:
    description: "JSON object containing all apps."
    required: true
  containerMode:
    description: "Container mode."
    required: true
  commit:
    description: "Reference for saving the cache."
    required: true
    default: ${{ github.sha }}
runs:
  using: 'node16'
  main: 'index.js'