{
 "title": "{{ .Values.site.name }}-{{ .Values.app.name }}",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(khaleesi_incoming_requests_total{site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(service, method, peer_site) (increase(khaleesi_incoming_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`OK: {{service}}/{{method}} called by {{peer_site}}`}}"
    },
    {
     "expr": "sum by(service, method, peer_site) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`NOK: {{service}}/{{method}} called by {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Incoming errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(status, service, method, peer_site) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{service}}/{{method}} called by {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(service, method, peer_site) (increase(khaleesi_outgoing_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`OK: {{service}}/{{method}} calling {{peer_site}}`}}"
    },
    {
     "expr": "sum by(service, method, peer_site) (increase(khaleesi_outgoing_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`NOK: {{service}}/{{method}} calling {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status, service, method, peer_site) (increase(khaleesi_outgoing_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{service}}/{{method}} calling {{peer_site}}`}}"
    }
   ]
  },
  {
   "title": "$service requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "service",
   "targets": [
    {}
   ]
  },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(khaleesi_version, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_incoming_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: OK - {{method}} called by {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    },
    {
     "expr": "sum by(khaleesi_version, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: NOK - {{method}} called by {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    }
   ]
  },
  {
   "title": "Incoming errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(status, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{method}} called by {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(khaleesi_version, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_outgoing_requests_total{status=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: OK - {{method}} called by {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    },
    {
     "expr": "sum by(khaleesi_version, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_incoming_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: NOK - {{method}} called by {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    }
   ]
  },
  {
   "title": "Outgoing errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status, method, peer_site, peer_app, peer_service, peer_method) (increase(khaleesi_outgoing_requests_total{status!=\"ok\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", service=\"$service\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{status}}: {{method}} calling {{peer_site}}.{{peer_app}}.{{peer_service}}/{{peer_method}}`}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum by (khaleesi_version) (khaleesi_health{site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", khaleesi_health=\"healthy\"}) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: healthy`}}"
    },
    {
     "expr": "sum by (khaleesi_version) (khaleesi_health{site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", khaleesi_health!=\"healthy\"}) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: not healthy`}}"
    }
   ]
  },
  {
   "title": "Instance health errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum by (khaleesi_health, khaleesi_version) (khaleesi_health{khaleesi_health!=\"healthy\",site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\"}) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: {{khaleesi_health}}`}}"
    }
   ]
  },
  {
   "title": "Instance Start/End",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by (khaleesi_version, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", result=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: {{action_crud_type}} - success`}}"
    },
    {
     "expr": "sum by (khaleesi_version, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", result!=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: {{action_crud_type}} - {{result}}`}}"
    }
   ]
  },
  {
   "title": "Instance Start/End Problems",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum by (khaleesi_version, action_crud_type, result) (increase(khaleesi_audit_event_total{target=\"core.core.server\", site=\"{{ .Values.site.name }}\", app=\"{{ .Values.app.name }}\", result!=\"success\", method=\"lifecycle\"}[$__rate_interval])) > 0",
     "legendFormat": "{{`{{khaleesi_version}}: {{action_crud_type}} - {{result}}`}}"
    }
   ]
  }
 ]
}