name: Get cached data
description: Get dependency cache, built protos, and base images
inputs:
  gate:
    description: The name of the gate
    required: true
  service:
    description: The name of the service
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - shell: bash
      run: pip install -r ./backend/${{ inputs.gate }}/${{ inputs.service }}/requirements-service.txt
    - uses: actions/download-artifact@v3
      with:
        name: protos-python
        path: backend/khaleesi/proto/
    - name: Load construction base
      uses: ./.github/actions/load-image
      with:
        image: khaleesi/base/backend-construction:${{ matrix.base-image-version }}
    - name: Load image base
      uses: ./.github/actions/load-image
      with:
        image: khaleesi/base/backend-image:${{ matrix.base-image-version }}
