apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: deployment
          image: deployment:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: deployment
              containerPort: 80



