apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "prometheus"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}-monitoring"
  labels:
    khaleesi-ninja: "monitoring"
    environment: "{{ .Values.environment.name }}"
    infrastructure: "prometheus"
