# khaleesi.ninja
environment:
  #name: "required name"
  #domain: "required domain"
gate:
  #name: "required name"
service:
  #name: "required name"
  #version: "required stable version"
  replicas: 1
  image_pull_policy: "Always"
  drop_database: false
type:
  #name: "required name"

# Kubernetes.
ingress:
  enabled: false
  path: "/"
  regex_path: false
  port: "service"

# Django.
django:
  enabled: false

# Database.
kubegres:
  enabled: false
  image: postgres:14.1
  port: 5432

# Monitoring.
probe:
  http:
    enabled: false
    readiness: "/monitoring/ready"
    liveness: "/monitoring/alive"

nginx_prometheus_exporter:
  enabled: false
  version: "0.9.0"

# gRPC.
grpc_web:
  enabled: false
  envoy_version: "v1.20.1"
grpcui:
  enabled: false
  version: "v1.2.0"
