apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: khaleesi-monitoring
  labels:
    khaleesi-ninja: environment
    environment: {{ .Values.environment.name }}
    infrastructure: grafana
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: khaleesi-ninja-{{ .Values.environment.name }}
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.khaleesi-ninja-{{ .Values.environment.name }}-monitoring.svc.cluster.local
