apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "grpc-web-envoy"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}"
  labels:
    khaleesi-ninja: "environment"
    environment: "{{ .Values.environment.name }}"
    infrastructure: "grpc-web-envoy"
data:
  envoy.yml: |-
  {{ .Files.Get "data/grpc-web-envoy.yml" | nindent 4 }}
