apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-web-envoy-configmap
  namespace: khaleesi-ninja-{{ .Values.environment }}
  labels:
    khaleesi-ninja: environment
    environment: {{ .Values.environment }}
data:
  envoy.yml: |-
  {{ .Files.Get "data/grpc-web-envoy.yml" | nindent 4 }}
