apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: ingress-class-{{ .Values.environment }}
  labels:
    khaleesi-ninja: environment
    environment: {{ .Values.environment }}
spec:
  controller: k8s.io/ingress-nginx
  parameters:
    kind: IngressParameters
    name: ingress-class
    namespace: khaleesi-ninja-{{ .Values.environment }}
    scope: Namespace
