apiVersion: v1
kind: ConfigMap
metadata:
  name: kubegres-initialization
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: environment
    environment: {{ .Values.environment.name }}
    infrastructure: kubegres-initialization
data:
  perform-initialization.sh: |-
  {{ .Files.Get "data/kubegres-perform-initialization.sh" | nindent 4 }}
  initialize-postgres.sql: |-
  {{ .Files.Get "data/kubegres-initialize-postgres.sql" | nindent 4 }}
  initialize-database.sql: |-
  {{ .Files.Get "data/kubegres-initialize-database.sql" | nindent 4 }}
