apiVersion: v1
kind: ConfigMap
metadata:
  name: kubegres-initialization-configuration
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: environment
    environment: {{ .Values.environment.name }}
    infrastructure: kubegres-initialization-configuration
data:
  initialization.sql: |-
  {{ .Files.Get "data/kubegres-initialization.sql" | nindent 4 }}
