apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: khaleesi-ninja-{{ .Values.environment.name }}-monitoring
  labels:
    khaleesi-ninja: monitoring
    environment: {{ .Values.environment.name }}
    infrastructure: prometheus
spec:
  alerting:
    alertmanagers:
      - name: kube-prometheus-kube-prome-alertmanager
        namespace: khaleesi-monitoring
        port: http-web
        pathPrefix: /
        apiVersion: v2
  image: quay.io/prometheus/prometheus:v2.31.1
  logLevel: info
  paused: false
  replicas: 1
  retention: 20d
  routePrefix: /
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: kube-prometheus
  serviceMonitorSelector:
    matchLabels:
      monitoring: khaleesi-ninja-{{ .Values.environment.name }}