@startuml
' ********************************************* STYLE **********************************************
<style>
agent {
  BackgroundColor lavender
  LineColor darkviolet
  FontColor darkviolet
}
rectangle {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
</style>

' ******************************************** OBJECTS *********************************************
agent metadata[
  Metadata
  ====
  reportedTimestamp
  loggedTimestamp
  ----
  httpRequestId
  grpcRequestId
  ----
  userId
  userType
  ----
  metaLoggerKhaleesiApp
  metaLoggerKhaleesiService
  metaLoggerGrpcService
  metaLoggerGrpcMethod
  ----
  podId
  errors
]

agent response [
  ResponseMetadata
  ====
  responseStatus
  ----
  reportedTimestamp
  loggedTimestamp
  duration
  ----
  errors
]

rectangle event [
  Event
  ====
  eventId
  ----
  targetType
  targetId
  targetOwnerId
  targetOwnerType
  ----
  actionCrudType
  actionCustomType
  actionResult
  actionDetails
]
rectangle grpc_request [
  GrpcRequest
  ====
  upstreamRequestId
  ----
  upstreamRequestKhaleesiApp
  upstreamRequestKhaleesiService
  upstreamRequestGrpcService
  upstreamRequestGrpcMethod
]
rectangle http_request [
  HttpRequest
  ====
  type
  language
  deviceId
  ----
  language
  ip
  useragent
  ----
  geolocation
  browser
  renderingAgent
  os
  deviceType
]

rectangle error [
  Error
  ====
  errorId
  ----
  status
  loglevel
  ----
  app
  service
  ----
  publicKey
  publicDetails
  ----
  privateMessage
  privateDetails
  stacktrace
]
rectangle query [
  Query
  ====
  queryId
  connection
  ----
  raw
  normalized
  ----
  tables
  columns
  ----
  reportedStart
  reportedEnd
]

' ******************************************* RELATIONS ********************************************
metadata ^-- event        #darkviolet;text:darkviolet
metadata ^-- grpc_request #darkviolet;text:darkviolet
metadata ^-- http_request #darkviolet;text:darkviolet
metadata ^-- query        #darkviolet;text:darkviolet
metadata ^-- error        #darkviolet;text:darkviolet

response ^-- grpc_request #darkviolet;text:darkviolet
response ^-- http_request #darkviolet;text:darkviolet

@enduml