@startuml
' ********************************************* STYLE **********************************************
<style>
agent {
  BackgroundColor lavender
  LineColor darkviolet
  FontColor darkviolet
}
rectangle {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
</style>

' ******************************************** OBJECTS *********************************************
agent metadata[
  Metadata
  ====
  reported_timestamp
  logged_timestamp
  ----
  http_request_id
  grpc_request_id
  ----
  user_id
  user_type
  ----
  meta_logger_khaleesi_app
  meta_logger_khaleesi_service
  meta_logger_grpc_service
  meta_logger_grpc_method
  ----
  pod_id
  errors
]

agent response [
  ResponseMetadata
  ====
  response_status
  ----
  reported_timestamp
  logged_timestamp
  duration
  ----
  errors
]

rectangle event [
  Event
  ====
  event_id
  ----
  target_type
  target_id
  target_owner_id
  target_owner_type
  ----
  action_crud_type
  action_custom_type
  action_result
  action_details
]
rectangle grpc_request [
  GrpcRequest
  ====
  upstream_request_id
  ----
  upstream_request_khaleesi_app
  upstream_request_khaleesi_service
  upstream_request_grpc_service
  upstream_request_grpc_method
]
rectangle http_request [
  HttpRequest
  ====
  type
  language
  device_id
  ----
  language
  ip
  useragent
  ----
  geolocation
  browser
  rendering_agent
  os
  device_type
]

rectangle error [
  Error
  ====
  error_id
  ----
  status
  loglevel
  ----
  app
  service
  ----
  public_key
  public_details
  ----
  private_message
  private_details
  stacktrace
]
rectangle query [
  Query
  ====
  query_id
  connection
  ----
  raw
  normalized
  ----
  tables
  columns
  ----
  reported_start
  reported_end
]

' ******************************************* RELATIONS ********************************************
metadata ^-- event        #darkviolet;text:darkviolet
metadata ^-- grpc_request #darkviolet;text:darkviolet
metadata ^-- http_request #darkviolet;text:darkviolet
metadata ^-- query        #darkviolet;text:darkviolet
metadata ^-- error        #darkviolet;text:darkviolet

response ^-- grpc_request #darkviolet;text:darkviolet
response ^-- http_request #darkviolet;text:darkviolet

@enduml