@startuml
' ********************************************* STYLE **********************************************
<style>
agent {
  BackgroundColor lavender
  LineColor darkviolet
  FontColor darkviolet
}
rectangle {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
</style>

' ******************************************** OBJECTS *********************************************
agent frontend
rectangle clocktower [
  Clocktower
  ====
  configure batch jobs
  execute batch jobs
  check batch job results
]
rectangle sawmill [
  Sawmill
  ====
  logging
  checking logs
  cleanup logs
  app call data
]

' ******************************************* RELATIONS ********************************************
frontend --> sawmill    #darkviolet;text:darkviolet : logging

clocktower --> sawmill #saddlebrown;text:saddlebrown : cleanup

clocktower --> sawmill #saddlebrown;text:saddlebrown : logging

@enduml