apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "grafana-datasource-{{ .Values.environment.name }}"
  namespace: "khaleesi-monitoring"
  labels:
    khaleesi-ninja: "environment"
    environment: "{{ .Values.environment.name }}"
    infrastructure: "grafana"
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: "1"
    datasources:
    - name: "khaleesi-ninja-{{ .Values.environment.name }}"
      type: "prometheus"
      access: "proxy"
      orgId: 1
      url: "http://prometheus-operated.khaleesi-ninja-{{ .Values.environment.name }}-monitoring.svc:9090/prometheus"
