# khaleesi.ninja.
environment:
  name: "development"
  domain: "development.khaleesi.ninja"
  development_credentials: true
service:
  version: "latest-development"
  replicas: 1
  image_pull_policy: "Never"

# Kubernetes.
ingress:
  root: false

# Database.
kubegres:
  replicas: 1
  size: 200Mi

# Monitoring.
prometheus:
  ingress: true
grafana:
  ingress: true
nginx_prometheus_exporter:
  enabled: false  # development builds don't export metrics.

# gRPC.
grpc_web:
  envoy_version: "v1.20-latest"
grpcui:
  version: "latest"
