# khaleesi.ninja.
environment:
  name: "development"
  domain: "development.khaleesi.ninja"
  development_credentials: true
app:
  version: "latest-development"
  replicas: 1
  image_pull_policy: "Never"

# Database.
kubegres:
  replicas: 1
  size: "200Mi"

# Monitoring.
prometheus:
  ingress: true
grafana:
  ingress: true
nginx_prometheus_exporter:
  enabled: false  # development builds don't export metrics.

# gRPC.
grpcui:
  version: "latest"
