environment:
  name: "integration"
  domain: "integration.khaleesi.ninja"
  development_credentials: true
kubegres:
  replicas: 1
  size: 200Mi
service:
  version: "latest-production"
  replicas: 1
  image_pull_policy: "Never"
grpc_web:
  envoy_version: "v1.20-latest"
grpcui:
  version: "latest"
