environment:
  name: "integration"
  domain: "integration.khaleesi.ninja"
kubegres:
  replicas: 1
  size: 200Mi
  development_credentials: true
service:
  version: "latest"
  replicas: 1
  image_pull_policy: "Never"
grpc_web:
  envoy_version: "v1.20-latest"
grpcui:
  version: "latest"
