{
 "title": "{{ .Values.gate.name }}",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "service", "query": { "query": "label_values(khaleesi_service)" } }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(khaleesi_service, peer_khaleesi_gate) (increase(khaleesi_incoming_requests_total{status=\"ok\", khaleesi_gate=\"{{ .Values.gate.name }}\"}[$__rate_interval]))",
     "legendFormat": "{{`OK: {{khaleesi_service}} called by {{peer_khaleesi_gate}}`}}"
    },
    {
     "expr": "sum by(khaleesi_service, peer_khaleesi_gate) (increase(khaleesi_incoming_requests_total{status!=\"ok\", khaleesi_gate=\"{{ .Values.gate.name }}\"}[$__rate_interval]))",
     "legendFormat": "{{`NOK: {{khaleesi_service}} called by {{peer_khaleesi_gate}}`}}"
    }
   ]
  },
  {
   "title": "Incoming errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(khaleesi_service, peer_khaleesi_gate, status) (increase(khaleesi_incoming_requests_total{status!=\"ok\", khaleesi_gate=\"{{ .Values.gate.name }}\"}[$__rate_interval]))",
     "legendFormat": "{{`{{status}}: {{khaleesi_service}} called by {{peer_khaleesi_gate}}`}}"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Instance health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (khaleesi_service) (khaleesi_health{khaleesi_gate=\"{{ .Values.gate.name }}\", khaleesi_health=\"healthy\"}) > 0",
     "legendFormat": "{{`{{khaleesi_service}}: healthy`}}"
    },
    {
     "expr": "sum by (khaleesi_service) (khaleesi_health{khaleesi_gate=\"{{ .Values.gate.name }}\", khaleesi_health!=\"healthy\"}) > 0",
     "legendFormat": "{{`{{khaleesi_service}}: not healthy`}}"
    }
   ]
  },
  {
   "title": "Instance health errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (khaleesi_health, khaleesi_service) (khaleesi_health{khaleesi_health!=\"healthy\",khaleesi_gate=\"{{ .Values.gate.name }}\"}) > 0",
     "legendFormat": "{{`{{khaleesi_service}}: {{khaleesi_health}}`}}"
    }
   ]
  }
 ]
}