@startuml
<style>
agent {
  BackgroundColor aliceblue
  LineColor darkblue
  FontColor darkblue
}
artifact {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
card {
  BackgroundColor lavender
  LineColor darkviolet
  FontColor darkviolet
}
</style>

folder base {
  artifact deployment as base_deployment
  artifact service as base_service
  agent ingress as base_ingress
  card kustomization as base_kustomization
}

folder service {
  agent "patch-ingress-host" as service_patch_ingress_host
  card service_kustomization [
    kustomization
    ====
    namePrefix
    commonLabels
    commonAnnotations
    images
    ----
    patches
  ]
}

folder environment {
  agent "patch-ingress-host" as environment_patch_ingress_host
  card environment_kustomization [
    kustomization
    ====
    patches
  ]
}

base <-- service
service <-- environment
@enduml
