@startuml
<style>
artifact {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
collections {
  BackgroundColor bisque
  LineColor saddlebrown
  FontColor saddlebrown
}
cloud {
  BackgroundColor lavender
  LineColor darkviolet
  FontColor darkviolet
}
</style>

actor user
package "frontgate" as frontgate {
  cloud ingress as front_ingress
  artifact service as front_service
  artifact deployment as front_deployment
  collections pod as front_pod
}

user --> front_ingress
front_ingress --> front_service
front_service --> front_deployment
front_deployment --> front_pod
@enduml
