@startuml
node base {
  artifact deployment as base_deployment
  card kustomization as base_kustomization
}

node service {
  card service_kustomization [
    kustomization
    ====
    namePrefix
    commonLabels
    commonAnnotations
    images
  ]
}

node environment {
  card environment_kustomization [
    kustomization
    ====
    namespace
  ]
}

base <-- service
service <-- environment
@enduml
