# Generated by Django 4.0.5 on 2023-06-24 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.TextField(default='UNKNOWN', unique=True)),
                ('name', models.TextField(default='UNKNOWN', unique=True)),
                ('description', models.TextField()),
                ('cronExpression', models.TextField()),
                ('action', models.TextField(default='UNKNOWN')),
                ('timelimit', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('batchSize', models.IntegerField(default=1000)),
                ('isCleanupJob', models.BooleanField(default=False)),
                ('cleanupDelay', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
