# Generated by Django 4.0.5 on 2023-01-31 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.TextField(default='UNKNOWN')),
                ('name', models.TextField(default='UNKNOWN')),
                ('description', models.TextField()),
                ('cron_expression', models.TextField()),
                ('cleanup_delay', models.DurationField(default=datetime.timedelta(0))),
                ('timelimit', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('batch_size', models.IntegerField(default=1000)),
                ('action', models.TextField(default='UNKNOWN')),
            ],
        ),
    ]
