name: Clean cached data
description: Clean cached data for a specific commit
inputs:
  commit:
    description: The commit for which to clean up
    required: true
    default: ${{ github.sha }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log('Start cleaning cache.')
          const caches = await github.rest.actions.getActionsCacheList({
            owner: context.repo.owner,
            repo: context.repo.repo,
            key: 'khaleesi/${{ inputs.commit }}/',
          })
          for (const cache of caches.data.actions_caches) {
            console.log(cache)
            github.rest.actions.deleteActionsCacheById({
              owner: context.repo.owner,
              repo: context.repo.repo,
              cache_id: cache.id,
            })
          }
          console.log('Finished cleaning cache.')
