name: Cache an image
description: Cache an image
inputs:
  image:
    description: Single image to be cached
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: /tmp/khaleesi/images/${{ inputs.image }}
        key: khaleesi/images/${{ inputs.image }}
    - shell: bash
      run: docker load -i /tmp/khaleesi/images/${{ inputs.image }}
