{{- if and .Values.environment.development_credentials .Values.django.enabled }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Values.site.name }}-{{ .Values.app.name }}-django"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}"
  labels:
    khaleesi-ninja: "app"
    site: "{{ .Values.site.name }}"
    name: "{{ .Values.app.name }}"
    type: "django"
type: "Opaque"
stringData:
  secretKey: "M07h3r0fDr460n5"
{{- end }}
