{{- if and .Values.environment.development_credentials .Values.kubegres.enabled }}
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Values.site.name }}-{{ .Values.app.name }}-kubegres"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}"
  labels:
    khaleesi-ninja: "app"
    site: "{{ .Values.site.name }}"
    app: "{{ .Values.app.name }}"
    type: "kubegres"
type: "Opaque"
stringData:
  password: "M07h3r0fDr460n5"
{{- end }}
