{{- if .Values.grpcui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-grpcui
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: grpcui
spec:
  replicas: 1
  selector:
    matchLabels:
      khaleesi-ninja: service
      gate: {{ .Values.gate.name }}
      name: {{ .Values.service.name }}
      type: grpcui
  template:
    metadata:
      labels:
        khaleesi-ninja: service
        gate: {{ .Values.gate.name }}
        name: {{ .Values.service.name }}
        type: grpcui
    spec:
      containers:
        - name: grpcui
          image: fullstorydev/grpcui:{{ .Values.grpcui.version }}
          imagePullPolicy: Always
          args: [ "-port=9000", "-plaintext", "{{ .Values.gate.name }}-{{ .Values.service.name }}:8000" ]
          ports:
            - name: grpcui
              containerPort: 9000
{{- end }}
