{{- if .Values.kubegres.enabled }}
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "{{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres"
  namespace: "khaleesi-ninja-{{ .Values.environment.name }}"
  labels:
    khaleesi-ninja: "service"
    gate: "{{ .Values.gate.name }}"
    name: "{{ .Values.service.name }}"
    type: "kubegres"
data:
  database: "{{ .Values.service.name }}"
  user: "{{ .Values.service.name }}"
{{- end }}
