{{ if .Values.kubegres.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-initialization
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: kubegres
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: create-user-and-database
          image: {{ .Values.kubegres.image }}
          command: [ "bin/bash", "-c", "psql -a -f /config/initialization.sql -v superUser=\"$KHALEESI_DATABASE_SUPERUSER\" -v superUserPassword=\"$KHALEESI_DATABASE_SUPERUSER_PASSWORD\" -v writeUser=\"$KHALEESI_DATABASE_WRITE_USER\" -v writePassword=\"$KHALEESI_DATABASE_WRITE_PASSWORD\" -v readUser=\"$KHALEESI_DATABASE_READ_USER\" -v readPassword=\"$KHALEESI_DATABASE_READ_PASSWORD\" -v database=\"$KHALEESI_DATABASE_NAME\"" ]
          volumeMounts:
            - name: kubegres-initialization-configuration
              readOnly: true
              mountPath: /config
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-configuration
                  key: host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-configuration
                  key: port
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-configuration
                  key: superUser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-credentials
                  key: superUserPassword
            - name: PGDATABASE
              value: postgres
            - name: KHALEESI_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-configuration
                  key: database
            - name: KHALEESI_DATABASE_SUPERUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-configuration
                  key: superUser
            - name: KHALEESI_DATABASE_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-kubegres-credentials
                  key: superUserPassword
            - name: KHALEESI_DATABASE_WRITE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-configuration
                  key: writeUser
            - name: KHALEESI_DATABASE_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-credentials
                  key: writePassword
            - name: KHALEESI_DATABASE_READ_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-configuration
                  key: readUser
            - name: KHALEESI_DATABASE_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-credentials
                  key: readPassword
      volumes:
        - name: kubegres-initialization-configuration
          configMap:
            name: kubegres-initialization-configuration
      restartPolicy: Never
  backoffLimit: 1
{{ end }}