{{ if .Values.kubegres.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres-initialization
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: kubegres
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: create-user-and-database
          image: {{ .Values.kubegres.image }}
          command: [ "bin/bash", "/config/perform-initialization.sh" ]
          volumeMounts:
            - name: kubegres-initialization
              readOnly: true
              mountPath: /config
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: host
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: port
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: superUser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: superUserPassword
            - name: KHALEESI_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
                  key: database
            - name: KHALEESI_DATABASE_SUPERUSER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: superUser
            - name: KHALEESI_DATABASE_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-kubegres
                  key: superUserPassword
            - name: KHALEESI_DATABASE_WRITE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
                  key: writeUser
            - name: KHALEESI_DATABASE_WRITE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
                  key: writePassword
            - name: KHALEESI_DATABASE_READ_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
                  key: readUser
            - name: KHALEESI_DATABASE_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
                  key: readPassword
      volumes:
        - name: kubegres-initialization
          configMap:
            name: kubegres-initialization
      restartPolicy: Never
  backoffLimit: 1
{{ end }}