{{ if and .Values.environment.development_credentials .Values.django.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-django-credentials
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: django
type: Opaque
stringData:
  secretKey: M07h3r0fDr460n5
{{ end }}
