{{ if and .Values.environment.development_credentials .Values.kubegres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gate.name }}-{{ .Values.service.name }}-kubegres
  namespace: khaleesi-ninja-{{ .Values.environment.name }}
  labels:
    khaleesi-ninja: service
    gate: {{ .Values.gate.name }}
    name: {{ .Values.service.name }}
    type: kubegres
type: Opaque
stringData:
  writePassword: M07h3r0fDr460n5
  readPassword: Br34k3r0fCh41n5
{{ end }}
