name: "Clean Cache"
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: "the prefix for which to clean the cache"
        required: true
        type: "string"
jobs:
  # Delete workflow runs inside the workflow to clean it up.
  clean-cache:
    runs-on: "ubuntu-latest"
    permissions:
      actions: "write"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Clean up cache."
        uses: "./.github/actions/clean-cache"
        with:
          prefix: ${{ inputs.prefix }}
