name: test-deployments
on:
  pull_request:
  push:
    paths:
      - '.github/**'
      - 'data/**'
      - 'kubernetes/**'
      - 'scripts/**'
      - 'backend/Dockerfile'
      - 'backend/execute_develop.sh'
      - 'backend/execute_production.sh'
      - 'backend/.dockerignore'
      - 'backend/requirements.txt'
      - 'frontgate/Dockerfile'
      - 'frontgate/execute_develop.sh'
      - 'frontgate/.dockerignore'
      - 'frontgate/nginx.conf'
      - 'frontgate/package.json'
jobs:
  # Make data lists available across jobs for use in matrix.
  matrix:
    runs-on: ubuntu-latest
    outputs:
      all-environments: ${{ steps.set-environments.outputs.full-json }}
      deploy-environments: ${{ steps.set-environments.outputs.deploy-json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - id: set-environments
        name: Read environments into matrix
        uses: ./.github/actions/set-json-output
        with:
          filename: data/environments.json

  # Test that the kubernetes deployments actually work.
  test-deployment:
    runs-on: ubuntu-latest
    needs: [ matrix ]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.matrix.outputs.deploy-environments) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          sudo dpkg -i minikube_latest_amd64.deb
          minikube start
      - name: Set up helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          sudo apt-get install apt-transport-https --yes
          echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Setup protoc
        uses: ./.github/actions/setup-protoc
      - name: Generate protos
        run: ./scripts/development/generate_protos.sh
      - name: Set up the cluster
        run: ./scripts/operations/setup_cluster.sh
      - name: Set up the environment
        run: ./scripts/operations/setup_environment.sh ${{ matrix.environment.name }}
      - name: Spin up the environment
        run: ./scripts/operations/deploy.sh ${{ matrix.environment.name }}
