name: Update Dependencies
on: [ push ]
jobs:
  # Figure out changes.
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend_dependencies: ${{ steps.filter.outputs.backend_dependencies }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            backend_dependencies:
              - 'backend/requirements.txt'
              - 'backend/requirements-develop.txt'

  # Update the pip cache with new requirements.
  update-pip-cache:
    runs-on: ubuntu-latest
    needs: [ changes ]
    if: ${{ needs.changes.outputs.backend_dependencies == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Fill python cache
        run: pip install -r ./backend/requirements.txt -r ./backend/requirements-develop.txt