name: Update Dependencies
on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - backend/requirements.txt
      - backend/requirements-develop.txt
      - frontgate/package.json
      - frontgate/package-lock.json
      - scripts/**

jobs:
  # Update the pip cache with new requirements.
  update-pip-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Fill python cache
        run: pip install -r ./backend/requirements.txt -r ./backend/requirements-develop.txt

  # Update the backend base images with new requirements.
  update-backend-base-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build backend base images
        uses: ./.github/actions/build-backend-base-images
